Repository GilDongMu/gildongmu-server, pull requests merged in 2024-03, with the labels that each got.

#6 chore: set up API docs using swagger
  gildongmu-api/build.gradle.kts
  gildongmu-api/src/main/java/codeit/api/config/SwaggerConfig.java
Labels: documentation, chore

#8 feat: add authentication related feature
  .github/workflows/deploy-dev.yml
  gildongmu-api/Dockerfile
  gildongmu-api/build.gradle.kts
  gildongmu-api/src/main/java/codeit/api/auth/controller/AuthController.java
  gildongmu-api/src/main/java/codeit/api/auth/dto/request/EmailCheckRequest.java
  gildongmu-api/src/main/java/codeit/api/auth/dto/request/LogInRequest.java
  gildongmu-api/src/main/java/codeit/api/auth/dto/request/SignUpRequest.java
  gildongmu-api/src/main/java/codeit/api/auth/dto/response/EmailCheckResponse.java
  gildongmu-api/src/main/java/codeit/api/auth/dto/response/TokenResponse.java
  gildongmu-api/src/main/java/codeit/api/auth/exception/AuthException.java
  gildongmu-api/src/main/java/codeit/api/auth/service/AuthService.java
  gildongmu-api/src/main/java/codeit/api/config/SecurityConfig.java
  gildongmu-api/src/main/java/codeit/api/exception/ErrorCode.java
  gildongmu-api/src/main/java/codeit/api/exception/GlobalExceptionHandler.java
  gildongmu-api/src/main/java/codeit/api/mock/controller/MockController.java
  gildongmu-api/src/main/java/codeit/api/mock/dto/response/MockResponse.java
  gildongmu-api/src/main/resources/application-dev.yml
  gildongmu-api/src/main/resources/application-local.yml
  gildongmu-api/src/test/java/codeit/ApiApplicationTests.java
  gildongmu-api/src/test/java/codeit/api/auth/controller/AuthControllerTest.java
  gildongmu-api/src/test/java/codeit/api/auth/service/AuthServiceTest.java
  gildongmu-api/src/test/java/codeit/api/config/WithMockCustomUser.java
  gildongmu-api/src/test/java/codeit/api/config/WithMockCustomUserSecurityContextFactory.java
  gildongmu-common/build.gradle.kts
  gildongmu-common/src/main/java/codeit/common/exception/ErrorCode.java
  gildongmu-common/src/main/java/codeit/common/security/AuthenticationDeniedHandler.java
  gildongmu-common/src/main/java/codeit/common/security/AuthenticationFailureEntryPoint.java
  gildongmu-common/src/main/java/codeit/common/security/JwtAuthenticationFilter.java
  gildongmu-common/src/main/java/codeit/common/security/JwtTokenManager.java
  gildongmu-common/src/main/java/codeit/common/security/UserDetailsServiceImpl.java
  gildongmu-common/src/main/java/codeit/common/security/UserPrincipal.java
  gildongmu-common/src/main/java/codeit/common/security/dto/response/AuthenticationExceptionResponse.java
  gildongmu-common/src/main/java/codeit/common/security/dto/transfer/TokenDto.java
  gildongmu-common/src/main/java/codeit/common/validator/Date.java
  gildongmu-common/src/main/java/codeit/common/validator/DateValidator.java
  gildongmu-common/src/main/java/codeit/common/validator/EnumValue.java
  gildongmu-common/src/main/java/codeit/common/validator/EnumValueValidator.java
  gildongmu-domain/src/main/java/codeit/domain/user/User.java
  gildongmu-domain/src/main/java/codeit/domain/user/constant/Gender.java
  gildongmu-domain/src/main/java/codeit/domain/user/constant/Role.java
  gildongmu-domain/src/main/java/codeit/domain/user/entity/User.java
  gildongmu-domain/src/main/java/codeit/domain/user/repository/UserRepository.java
Labels: feature

#15 feat: update the CORS policy that allows request from FE
  gildongmu-api/src/main/java/codeit/api/config/WebConfig.java
Labels: bug

#17 refactor: use implementation instead of unnecessary inheritance
  gildongmu-common/src/main/java/codeit/common/security/OAuth2LoginSuccessHandler.java
  gildongmu-common/src/main/java/codeit/common/security/OAuth2LoginUser.java
Labels: refactor

#19 chore: build a chat server
  gildongmu-chat/Dockerfile
  gildongmu-chat/build.gradle.kts
  gildongmu-chat/src/main/java/codeit/ChatApplication.java
  gildongmu-chat/src/main/java/codeit/chat/config/MongoConfig.java
  gildongmu-chat/src/main/resources/application-dev.yml
  gildongmu-chat/src/main/resources/application-local.yml
  gildongmu-chat/src/test/java/codeit/ChatApplicationTests.java
  settings.gradle.kts
Labels: feature

#26 feat: add kakao social login feature with oAuth2
  .github/workflows/deploy-dev-api.yml
  gildongmu-api/Dockerfile
  gildongmu-api/src/main/java/codeit/api/security/OAuth2Registration.java
  gildongmu-api/src/main/java/codeit/api/security/OAuth2UserServiceImpl.java
  gildongmu-api/src/main/resources/application-dev.yml
  gildongmu-api/src/main/resources/application-local.yml
Labels: feature, chore

#28 chore: change semicolon to comma
  gildongmu-api/src/main/java/codeit/api/exception/ErrorCode.java
Labels: bug, chore

#53 feat: add profile image to single post view
  gildongmu-api/src/main/java/codeit/api/post/dto/response/PostResponse.java
Labels: enhancement

#61 add feature to retrieve room
  gildongmu-api/src/main/java/codeit/api/room/controller/RoomController.java
  gildongmu-api/src/main/java/codeit/api/room/dto/response/RoomInfoResponse.java
  gildongmu-api/src/main/java/codeit/api/room/dto/response/RoomResponse.java
  gildongmu-api/src/main/java/codeit/api/room/service/RoomService.java
  gildongmu-api/src/test/java/codeit/api/room/controller/RoomControllerTest.java
  gildongmu-api/src/test/java/codeit/api/room/service/RoomServiceTest.java
  gildongmu-chat/src/test/java/codeit/chat/service/ChatServiceTest.java
  gildongmu-domain/src/main/java/codeit/domain/room/entity/Room.java
  gildongmu-domain/src/main/java/codeit/domain/room/repository/RoomRepository.java
Labels: feature

#81 feat: add comment feature
  gildongmu-api/src/main/java/codeit/api/comment/controller/CommentController.java
  gildongmu-api/src/main/java/codeit/api/comment/dto/request/CommentCreateRequest.java
  gildongmu-api/src/main/java/codeit/api/comment/dto/request/CommentUpdateRequest.java
  gildongmu-api/src/main/java/codeit/api/comment/dto/response/CommentListResponse.java
  gildongmu-api/src/main/java/codeit/api/comment/dto/response/CommentUpdateResponse.java
  gildongmu-api/src/main/java/codeit/api/comment/exception/CommentException.java
  gildongmu-api/src/main/java/codeit/api/comment/service/CommentService.java
  gildongmu-api/src/main/java/codeit/api/exception/ErrorCode.java
  gildongmu-api/src/main/java/codeit/api/exception/GlobalExceptionHandler.java
  gildongmu-domain/src/main/java/codeit/domain/comment/entity/Comment.java
  gildongmu-domain/src/main/java/codeit/domain/comment/repository/CommentRepository.java
  gildongmu-domain/src/main/java/codeit/domain/post/entity/Post.java
Labels: feature

#89 fix: remove oauth2 user login session when token issuing is success
  gildongmu-api/src/main/java/codeit/api/oauth2/service/OAuth2LoginService.java
  gildongmu-api/src/test/java/codeit/api/oauth2/service/OAuth2LoginServiceTest.java
Labels: enhancement

#90 fix: add s3 configuration bean in test code
  gildongmu-api/src/test/java/codeit/ApiApplicationTests.java
  gildongmu-chat/src/test/java/codeit/ChatApplicationTests.java
Labels: bug

#92 refactor: use optional and extract method for readability
  gildongmu-api/src/main/java/codeit/api/auth/service/AuthService.java
  gildongmu-api/src/main/java/codeit/api/oauth2/service/OAuth2LoginService.java
  gildongmu-api/src/main/java/codeit/api/user/service/UserService.java
  gildongmu-domain/src/main/java/codeit/domain/user/entity/User.java
Labels: refactor

#108 fix: fix sorting problem posts are not sorted properly
  gildongmu-api/src/main/java/codeit/api/post/controller/PostController.java
  gildongmu-api/src/main/java/codeit/api/post/service/PostService.java
  gildongmu-domain/src/main/java/codeit/domain/post/repository/PostRepository.java
Labels: bug
